# Generated by Django 2.2.4 on 2019-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='helpFile',
            field=models.FileField(default=1, upload_to='help_files'),
            preserve_default=False,
        ),
    ]
